FROM python:3.11-slim

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir semgrep bandit flask flask-cors gunicorn

EXPOSE 10000
ENV PORT=10000
CMD ["gunicorn", "backend.app:app", "--bind", "0.0.0.0:$PORT"]

